- name: This playbook will install nginx, configures web root folder, deploys custom web page
  hosts: all
  tasks:
    - name: Install nginx in Ubuntu node
      apt: name=nginx state=latest update_cache=yes

    - name: Install curl utility in Ubuntu node
      apt: name=curl state=latest

    - name: Check if web page is accessible in Ubuntu node
      shell: curl http://localhost:80
      register: response
      ignore_errors: yes

    - debug: var=response

    - name: Start the nginx web server in Ubuntu node
      when: response.failed == true
      shell: nginx 

